SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `users`.`registro` (`id` BIGINT NOT NULL AUTO_INCREMENT , `user` VARCHAR(20) NOT NULL , `edad` VARCHAR(10) NOT NULL , `password` VARCHAR(15) NOT NULL , `provincia` VARCHAR(20) NOT NULL , `canton` VARCHAR(40) NOT NULL , `email` VARCHAR(40) NOT NULL , `latitud` VARCHAR(10) NOT NULL , `longitud` VARCHAR(10) NOT NULL , PRIMARY KEY (`id`), UNIQUE (`user`), UNIQUE (`email`)) ENGINE = InnoDB;

CREATE TABLE `users`.`coordenadas` (`id` INT NOT NULL AUTO_INCREMENT , `latitud` FLOAT NOT NULL , `longitud` FLOAT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
